-- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, SUM(P.PRICE*SALES_AMOUNT) SALES
# FROM OFFLINE_SALE O LEFT OUTER JOIN PRODUCT P ON O.PRODUCT_ID=P.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE;


WITH CTE AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SA
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)
SELECT P.PRODUCT_CODE, P.PRICE*CTE.SA AS SLAES
FROM PRODUCT P
LEFT JOIN CTE ON P.PRODUCT_ID = CTE.PRODUCT_ID
ORDER BY SLAES DESC, PRODUCT_CODE ASC;

# SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SA
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID