-- 코드를 입력하세요
# SELECT *
# FROM ANIMAL_OUTS OUTS
# LEFT OUTER JOIN ANIMAL_INS INS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE INS.NAME IS NULL
# ORDER BY OUTS.ANIMAL_ID;

# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O;
# SELECT I.ANIMAL_ID, I.NAME
# FROM ANIMAL_INS I;
# WITH CTE AS ()
#     SELECT O.ANIMAL_ID, O.NAME
#     FROM ANIMAL_OUTS O
#     LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# )
# SELECT *
# FROM CTE
# WHERE 
# WHERE I.NAME IS NULL
# ORDER BY O.ANIMAL_ID, O.NAME
# ;


SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
WHERE NOT EXISTS (
    SELECT I.ANIMAL_ID
    FROM ANIMAL_INS I
    WHERE O.ANIMAL_ID = I.ANIMAL_ID
)
ORDER BY O.ANIMAL_ID, O.NAME;

