# SELECT A.NAME, A.DATETIME
# FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.ANIMAL_ID IS NULL
# ORDER BY A.DATETIME
# LIMIT 3



SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS(
    SELECT *
    FROM ANIMAL_OUTS O
    WHERE I.ANIMAL_ID=O.ANIMAL_ID
)
ORDER BY I.DATETIME
LIMIT 3;

