# WITH EMP_SCORES AS (
#     SELECT SUM(G.SCORE) AS TOTAL_SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
#     FROM HR_EMPLOYEES E
#     LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
#     GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# )
# SELECT MAX(TOTAL_SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
# FROM EMP_SCORES;


WITH EMP_SCORES AS (
    SELECT SUM(G.SCORE) AS TOTAL_SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
    FROM HR_EMPLOYEES E
    LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
)
SELECT TOTAL_SCORE SCORE ,EMP_NO, EMP_NAME, POSITION, EMAIL
FROM EMP_SCORES
WHERE TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM EMP_SCORES);